server:
  port: 8082
spring:
  application:
    name: service-DepartamentoAbanicos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
ribbon:
  ConnectTimeOut: 3000
  ReadTimeOut: 10000
hystrix:
  commant:
    default:
      execution:
        isolation:
          thread:
            timeInMilliseconds: 20000